workflows:
  ios-workflow:
    name: iOS Build - Ad Hoc Signed
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Create build directory
        script: mkdir -p dist && echo '<h1>VocabWorld</h1>' > dist/index.html
      - name: Install Capacitor CLI
        script: npm install -g @capacitor/cli
      - name: Add iOS platform
        script: npx cap add ios
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Create Ad Hoc Signed IPA
        script: |
          # Create a self-signed certificate for ad-hoc distribution
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          
          # Create a simple mobileprovision for ad-hoc
          mkdir -p ios/App/App/
          
          # Build with ad-hoc signing
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            archive
            
          # Create IPA manually
          mkdir -p $CM_BUILD_DIR/Payload
          cp -r $CM_BUILD_DIR/App.xcarchive/Products/Applications/App.app $CM_BUILD_DIR/Payload/
          cd $CM_BUILD_DIR
          zip -r VocabWorld.ipa Payload/
    artifacts:
      - $CM_BUILD_DIR/VocabWorld.ipa
    publishing:
      email:
        recipients:
          - wocabworldapp@example.com
        notify:
          success: true
          failure: true