workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Create build directory
        script: mkdir -p dist && echo '<h1>VocabWorld</h1>' > dist/index.html
      - name: Install Capacitor CLI
        script: npm install -g @capacitor/cli
      - name: Add iOS platform
        script: npx cap add ios
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Configure code signing
        script: |
          # Disable automatic code signing for CI builds
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/' ios/App/App.xcodeproj/project.pbxproj
          sed -i '' 's/DEVELOPMENT_TEAM = .*;/DEVELOPMENT_TEAM = "";/' ios/App/App.xcodeproj/project.pbxproj
      - name: Build iOS for Simulator
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -derivedDataPath $CM_BUILD_DIR/DerivedData \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            build
      - name: Create App Bundle
        script: |
          mkdir -p $CM_BUILD_DIR/VocabWorld.app
          cp -r $CM_BUILD_DIR/DerivedData/Build/Products/Debug-iphonesimulator/App.app/* $CM_BUILD_DIR/VocabWorld.app/
          echo "VocabWorld iOS app built successfully!"
    artifacts:
      - $CM_BUILD_DIR/VocabWorld.app/**/*