workflows:
  ios-workflow:
    name: VocabWorld iOS - Capacitor Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Install Capacitor CLI
        script: npm install -g @capacitor/cli
      - name: Build Next.js app
        script: |
          # Build the Next.js app for production
          npm run build
          
          # Verify the build was successful
          echo "✅ Next.js build completed"
          ls -la dist/
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Build unsigned iOS app
        script: |
          cd ios/App
          
          echo "🔧 Building unsigned iOS app for development testing..."
          
          # Build without code signing
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath $CM_BUILD_DIR/VocabWorld.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE="" \
            archive
          
          echo "📦 Creating IPA package..."
          
          # Create IPA manually
          if [ -d "$CM_BUILD_DIR/VocabWorld.xcarchive/Products/Applications/App.app" ]; then
            mkdir -p $CM_BUILD_DIR/Payload
            cp -r "$CM_BUILD_DIR/VocabWorld.xcarchive/Products/Applications/App.app" "$CM_BUILD_DIR/Payload/"
            
            cd $CM_BUILD_DIR
            zip -r VocabWorld.ipa Payload/
            
            echo "📁 File size: $(ls -lh VocabWorld.ipa | awk '{print $5}')"
            
            # Create installation guide
            cat > iPhone_Installation_Guide.txt << 'GUIDE'
          📱 VocabWorld Installation Guide - iPhone Testing

          🚨 INSTALL ON YOUR IPHONE:

          1. 📥 Download VocabWorld.ipa from Codemagic artifacts
          2. 🌐 Go to diawi.com on your computer
          3. 📱 Upload VocabWorld.ipa to Diawi
          4. 📲 Open the Diawi link on your iPhone in Safari
          5. ✅ Tap "Install" when prompted
          6. ⚙️ Go to Settings > General > VPN & Device Management
          7. 👨‍💻 Find "VocabWorld Development Team" and tap "Trust"
          8. 🚀 Open VocabWorld app to test!

          📱 What to Expect:
          - Native iOS app (not Safari web view)
          - Purple status bar background
          - Capacitor native functionality
          - Your Next.js VocabWorld content

          ✨ This is a complete native iOS app built with Capacitor!
          GUIDE
            
            # Verify the file exists and has content
            if [ -f "VocabWorld.ipa" ] && [ -s "VocabWorld.ipa" ]; then
              echo "🎯 VocabWorld.ipa is ready for download!"
              echo "📋 IPA contents:"
              unzip -l VocabWorld.ipa | head -10
            else
              echo "❌ IPA file is empty or missing"
            fi
          else
            echo "❌ App bundle not found in archive"
            echo "🔍 Available files:"
            find $CM_BUILD_DIR -name "*.app" -type d
            find $CM_BUILD_DIR -name "*.xcarchive" -type d
          fi
    artifacts:
      - VocabWorld.ipa
      - iPhone_Installation_Guide.txt
      - ios/App/build/Release-iphoneos/*.app