workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Create build directory
        script: mkdir -p dist && echo '<h1>VocabWorld</h1>' > dist/index.html
      - name: Install Capacitor CLI
        script: npm install -g @capacitor/cli
      - name: Add iOS platform
        script: npx cap add ios
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Build iOS
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportPath $CM_BUILD_DIR/export \
            -exportOptionsPlist ios/App/exportOptions.plist
    artifacts:
      - $CM_BUILD_DIR/export/*.ipa